# Generated by Django 5.2.11 on 2026-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_travelproject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
