# Generated by Django 5.2.11 on 2026-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_travelproject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
